include ../../../setup/properties.mk
 
SRCS=$(wildcard *.c)
ALLOBJS=$(patsubst %.c,target/%.o,$(SRCS))
ALL=target/libSapiInfra.so

CFLAGS+=-I../../../packages/_install/include -I../../include -I./include -fPIC

LDFLAGS+= -L../../../packages/_install/lib -lssl -lcrypto -lpthread

install: $(ALL)
	@mkdir -p _install/lib
	@cp $(ALL) _install/lib

all: $(ALLOBJS) $(ALL) install

$(ALL): $(ALLOBJS)
	@echo "LD $@"
	@$(CC) $(CFLAGS) -shared -Wl,-soname,libSapiInfra.so -o $@ $^ $(LDFLAGS)

include ../../../setup/common.mk

